#  [[main]]
#  name = "Home"
#  identifier = "home"
#  weight = 100
#  url = "/"

#  [[main]]
#  name = "Blog"
#  weight = 200
#  identifier = "posts"
#  url = "/post/"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/"

#  [[main]]
#  name = "Contact"
#  weight = 400
#  identifier = "contact"
#  url = "/contact/"

#  [[footer]]
#  name = "imprint"
#  weight = 1
#  identifier = "imprint"
#  url = "/imprint/"